//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://smartbear.com", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SampleTestClass", Namespace="http://smartbear.com")]
    public partial class SampleTestClass : object
    {
        
        private double XField;
        
        private double YField;
        
        private string NameField;
        
        private ServiceReference.ArrayOfInt IntArrayField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ServiceReference.ArrayOfInt IntArray
        {
            get
            {
                return this.IntArrayField;
            }
            set
            {
                this.IntArrayField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smartbear.com", ConfigurationName="ServiceReference.SampleWebServiceSoap")]
    public interface SampleWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartbear.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.HelloWorldResponse> HelloWorldAsync(ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartbear.com/GetArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetArrayResponse> GetArrayAsync(ServiceReference.GetArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartbear.com/GetCurrentTime", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetCurrentTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartbear.com/GetSampleObject", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetSampleObjectResponse> GetSampleObjectAsync(ServiceReference.GetSampleObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartbear.com/SetSampleObject", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SetSampleObjectResponse> SetSampleObjectAsync(ServiceReference.SetSampleObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartbear.com/GetXmlData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetXmlDataResponse> GetXmlDataAsync(ServiceReference.GetXmlDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(ServiceReference.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(ServiceReference.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smartbear.com")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArray", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.GetArrayRequestBody Body;
        
        public GetArrayRequest()
        {
        }
        
        public GetArrayRequest(ServiceReference.GetArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetArrayRequestBody
    {
        
        public GetArrayRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArrayResponse", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.GetArrayResponseBody Body;
        
        public GetArrayResponse()
        {
        }
        
        public GetArrayResponse(ServiceReference.GetArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smartbear.com")]
    public partial class GetArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.ArrayOfInt GetArrayResult;
        
        public GetArrayResponseBody()
        {
        }
        
        public GetArrayResponseBody(ServiceReference.ArrayOfInt GetArrayResult)
        {
            this.GetArrayResult = GetArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSampleObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSampleObject", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.GetSampleObjectRequestBody Body;
        
        public GetSampleObjectRequest()
        {
        }
        
        public GetSampleObjectRequest(ServiceReference.GetSampleObjectRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smartbear.com")]
    public partial class GetSampleObjectRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int no;
        
        public GetSampleObjectRequestBody()
        {
        }
        
        public GetSampleObjectRequestBody(int no)
        {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSampleObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSampleObjectResponse", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.GetSampleObjectResponseBody Body;
        
        public GetSampleObjectResponse()
        {
        }
        
        public GetSampleObjectResponse(ServiceReference.GetSampleObjectResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smartbear.com")]
    public partial class GetSampleObjectResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.SampleTestClass GetSampleObjectResult;
        
        public GetSampleObjectResponseBody()
        {
        }
        
        public GetSampleObjectResponseBody(ServiceReference.SampleTestClass GetSampleObjectResult)
        {
            this.GetSampleObjectResult = GetSampleObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetSampleObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetSampleObject", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.SetSampleObjectRequestBody Body;
        
        public SetSampleObjectRequest()
        {
        }
        
        public SetSampleObjectRequest(ServiceReference.SetSampleObjectRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smartbear.com")]
    public partial class SetSampleObjectRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.SampleTestClass obj;
        
        public SetSampleObjectRequestBody()
        {
        }
        
        public SetSampleObjectRequestBody(ServiceReference.SampleTestClass obj)
        {
            this.obj = obj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetSampleObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetSampleObjectResponse", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.SetSampleObjectResponseBody Body;
        
        public SetSampleObjectResponse()
        {
        }
        
        public SetSampleObjectResponse(ServiceReference.SetSampleObjectResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smartbear.com")]
    public partial class SetSampleObjectResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetSampleObjectResult;
        
        public SetSampleObjectResponseBody()
        {
        }
        
        public SetSampleObjectResponseBody(string SetSampleObjectResult)
        {
            this.SetSampleObjectResult = SetSampleObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlData", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.GetXmlDataRequestBody Body;
        
        public GetXmlDataRequest()
        {
        }
        
        public GetXmlDataRequest(ServiceReference.GetXmlDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetXmlDataRequestBody
    {
        
        public GetXmlDataRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlDataResponse", Namespace="http://smartbear.com", Order=0)]
        public ServiceReference.GetXmlDataResponseBody Body;
        
        public GetXmlDataResponse()
        {
        }
        
        public GetXmlDataResponse(ServiceReference.GetXmlDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smartbear.com")]
    public partial class GetXmlDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetXmlDataResult;
        
        public GetXmlDataResponseBody()
        {
        }
        
        public GetXmlDataResponseBody(System.Xml.XmlElement GetXmlDataResult)
        {
            this.GetXmlDataResult = GetXmlDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface SampleWebServiceSoapChannel : ServiceReference.SampleWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class SampleWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference.SampleWebServiceSoap>, ServiceReference.SampleWebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SampleWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SampleWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SampleWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SampleWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SampleWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.HelloWorldResponse> ServiceReference.SampleWebServiceSoap.HelloWorldAsync(ServiceReference.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.HelloWorldResponse> HelloWorldAsync()
        {
            ServiceReference.HelloWorldRequest inValue = new ServiceReference.HelloWorldRequest();
            inValue.Body = new ServiceReference.HelloWorldRequestBody();
            return ((ServiceReference.SampleWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetArrayResponse> ServiceReference.SampleWebServiceSoap.GetArrayAsync(ServiceReference.GetArrayRequest request)
        {
            return base.Channel.GetArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetArrayResponse> GetArrayAsync()
        {
            ServiceReference.GetArrayRequest inValue = new ServiceReference.GetArrayRequest();
            inValue.Body = new ServiceReference.GetArrayRequestBody();
            return ((ServiceReference.SampleWebServiceSoap)(this)).GetArrayAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetCurrentTimeAsync()
        {
            return base.Channel.GetCurrentTimeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetSampleObjectResponse> ServiceReference.SampleWebServiceSoap.GetSampleObjectAsync(ServiceReference.GetSampleObjectRequest request)
        {
            return base.Channel.GetSampleObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetSampleObjectResponse> GetSampleObjectAsync(int no)
        {
            ServiceReference.GetSampleObjectRequest inValue = new ServiceReference.GetSampleObjectRequest();
            inValue.Body = new ServiceReference.GetSampleObjectRequestBody();
            inValue.Body.no = no;
            return ((ServiceReference.SampleWebServiceSoap)(this)).GetSampleObjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SetSampleObjectResponse> ServiceReference.SampleWebServiceSoap.SetSampleObjectAsync(ServiceReference.SetSampleObjectRequest request)
        {
            return base.Channel.SetSampleObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SetSampleObjectResponse> SetSampleObjectAsync(ServiceReference.SampleTestClass obj)
        {
            ServiceReference.SetSampleObjectRequest inValue = new ServiceReference.SetSampleObjectRequest();
            inValue.Body = new ServiceReference.SetSampleObjectRequestBody();
            inValue.Body.obj = obj;
            return ((ServiceReference.SampleWebServiceSoap)(this)).SetSampleObjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetXmlDataResponse> ServiceReference.SampleWebServiceSoap.GetXmlDataAsync(ServiceReference.GetXmlDataRequest request)
        {
            return base.Channel.GetXmlDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetXmlDataResponse> GetXmlDataAsync()
        {
            ServiceReference.GetXmlDataRequest inValue = new ServiceReference.GetXmlDataRequest();
            inValue.Body = new ServiceReference.GetXmlDataRequestBody();
            return ((ServiceReference.SampleWebServiceSoap)(this)).GetXmlDataAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SampleWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SampleWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SampleWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://secure.smartbearsoftware.com/samples/testcomplete14/webservices/Service.as" +
                        "mx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SampleWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://secure.smartbearsoftware.com/samples/testcomplete14/webservices/Service.as" +
                        "mx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SampleWebServiceSoap,
            
            SampleWebServiceSoap12,
        }
    }
}
